# Generated by Django 3.0.5 on 2020-05-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='cert',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
