# Generated by Django 3.0.5 on 2020-06-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200531_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birthday',
            field=models.DateField(),
        ),
    ]
